# Generated by Django 4.2.20 on 2025-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/avatar.svg', null=True, upload_to='avatars/'),
        ),
    ]
